default-resources:
    slurm_partition: core
    slurm_account: naiss2023-5-461
    runtime: 30 # minutes
    mem_gb: 1 # 1G 
    tasks: 1
    nodes: 1
    cpus_per_task: 1 
    slurm_extra: "'--mail-user=zk.montes10@uniandes.edu.co --mail-type=all'"
